### ISSUE TITLE
Question about test and evaluate

### ISSUE THREAD

**Issue by G-1nOnly** [chenhsuanlin/bundle-adjusting-NeRF#26]
I would like to ask a question about **the difference between test and evaluate**, I notice that for the "test-optim" mode, you would still perform some refinement and for the "eval" part, you evaluate the results, so if I have trained a model, I'm going to test the model and regenerate the figure, I should use the "test-optim" mode or the "eval" mode, from my understanding, I should use the "test-optim" mode? I'd appreciate it if you answered my questions about the difference about test and evaluate.

By the way, great works and thank you in advance!!!

**Comment by chenhsuanlin** [comment]
Hi @G-1nOnly, both modes are for evaluation: `eval` is the default evaluation mode and `test-optim` is a special mode that
- [enables backprop](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/barf.py#L153) for test-time optimization (disabled by default), and
- samples random rays instead of rendering the entire image, as in training mode ([here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L204) and [here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L219)).

You can think of the `test-optim` mode as the training (optimization) mode for evaluation. Hope this helps!
