### ISSUE TITLE
How to optimize intrinsics as well?

### ISSUE THREAD

**Issue by Ir1d** [chenhsuanlin/bundle-adjusting-NeRF#52]
Hi @chenhsuanlin great work!

I'm trying BARF on my custom data, and it shows promising results. However, I'm wondering whether the performance will be better if we optimize the intrinsic as well. Do you feel it's doable? If so, could you please guide me on where I should be modifying? Thanks!

**Comment by chenhsuanlin** [comment]
Hi @Ir1d, although I have not tried it myself, I think it's certainly possible. You could create learnable parameters for the intrinsics as I did for poses [here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/barf.py#L24-L31) so that they are optimizable. I would suggest looking into [NeRF--](https://nerfmm.active.vision/) for more details.
