### ISSUE TITLE
Why not use batch_size, epoch, just iter training

### ISSUE THREAD

**Issue by Pluto-wei** [chenhsuanlin/bundle-adjusting-NeRF#65]
I want to adapt the code to multi-GPUs training, and encountered some problems in the process of adding DDP (DistributedDataParallel).
May I ask why nerf and barf do not use batch_size, regardless of epoch training, directly use iter training?
This question is asked because DDP needs to use sampler to divide data across GPUs in each epoch. I don’t know if only iter and not disrupting data will affect performance.

**Comment by chenhsuanlin** [comment]
This is because it randomly samples pixels from all the training images in each iteration, so there's really no notion of epochs anymore (this follows the practice of the original NeRF). You _could_ batch images and then sample pixels from these selected images (in fact, this was how I initially developed the code); statistically all the pixels would still have equal probabilities of being seen in the long term, but it actually results in biased gradients towards these selected images, and empirically we found that it could find suboptimal results.

There are some ways I can think of to make it work with DDP:
1. The current code caches all training images in the GPU memory, so you could do the same for all GPUs and let each thread run its own pixel sampler. This may be the faster hack, but will be more memory wasteful.
2. Modify the code to train in epoch mode, which is what you're looking for (should not be difficult). If the effective batch size in DDP approaches the dataset size (i.e. number of images), this bias should be well mitigated as well.

Hope this helps!
