### ISSUE TITLE
About the Poses are relative relationship

### ISSUE THREAD

**Issue by hhhmoan** [chenhsuanlin/bundle-adjusting-NeRF#67]
In the nerf scene, pose is actually only relative. It means that uniform rotation or scaling can be performed without changing the optimization result of nerf. My question is how BARF optimizes pose so as to achieve a convergent result.
It may be necessary to use a picture without optimizing the pose as an anchor point?
thank you

**Comment by chenhsuanlin** [comment]
Hi @hhhmoan, the solution would be ambiguous up to a similarity transform (which is why we run Procrustes analysis to align the cameras before evaluating). It is true that BARF may converge to different solutions, but in our case, it doesn't really matter as long as it is a valid one -- it will still converge. Anchoring one of the cameras would indeed make the solution unique, but it would also converge a bit slower as there is less flexibility in how the scene and cameras could be updated.
Hope this helps!
