### ISSUE TITLE
How to create a 3D-model from the output of iphone experiment?

### ISSUE THREAD

**Issue by franciscoWizz** [chenhsuanlin/bundle-adjusting-NeRF#8]
Hi Chen-Hsuan,

I successfully created an experiment in the iphone.py style. That is, without any information of camera poses. Is it possible to  create a 3D model from the output?

Thanks in advance,

**Comment by chenhsuanlin** [comment]
Hi @franciscoWizz, you can run marching cubes on the volume density field to extract a 3D mesh. Although I don't have the script to run off-the-shelf, the basic idea is to sample the volume density in a dense voxel grid, so you could extract a density voxel grid as the intermediate output. You can then run marching cubes (e.g. with PyMCubes) to extract the mesh.

Here is an example [script](https://github.com/bmild/nerf/blob/master/extract_mesh.ipynb) from the NeRF repo to run marching cubes, and it should be modifiable to fit this repo.
Hope this helps!

**Comment by chenhsuanlin** [comment]
Closing for now, please feel free to reopen if you have further questions!

**Comment by martinarroyo** [comment]
Here's a very crude attempt to do this. It would be great if you could give me some feedback about it. The code is based on a mixture between `evaluate.py` and the NeRF script that you mentioned.

```python
import numpy as np
import os, sys, time
import torch
import importlib
from tqdm import tqdm
import trimesh
import options
import mcubes

opt_cmd = options.parse_arguments(sys.argv[1:])
opt = options.set(opt_cmd=opt_cmd)

with torch.cuda.device(opt.device), torch.no_grad(): # I am using some functions directly that originally were under this decorator. Not using it results in OOM.

  model = importlib.import_module("model.{}".format(opt.model))
  m = model.Model(opt)

  m.load_dataset(opt, eval_split="test")
  m.build_networks(opt)

  m.restore_checkpoint(opt)
  N = 256
  t = np.linspace(-1.2, 1.2, N + 1)

  query_pts = np.stack(np.meshgrid(t, t, t), -1).astype(np.float32)
  sh = query_pts.shape
  flat = query_pts.reshape([-1, 3])
  batch_size = 1

  chunk = 1024
  densities = []
  for i in tqdm(range(0, flat.shape[0], chunk)):
    points = torch.from_numpy(np.expand_dims(flat[i:i + chunk],
                                             axis=0)).to(opt.device)
    ray = points
    points_3D_samples = points
    ray_unit_samples = None
    opt.nerf.view_dep = False
    rgb_samples, density_samples = m.graph.nerf.forward(
        opt, points_3D_samples, ray_unit=None,
        mode=None)

    densities.append(density_samples.detach().cpu().numpy())
  densities = np.concatenate(densities, axis=1)
  densities = np.reshape(densities, list(query_pts.shape[:-1]) + [-1])

  sigma = np.maximum(densities[..., -1], 0.)

  threshold = 25.
  vertices, triangles = mcubes.marching_cubes(sigma, threshold)

  mesh = trimesh.Trimesh(vertices / N - .5, triangles)
  mesh.show()

```
It seems to work on the Lego model:
![Screenshot from 2021-12-13 18-57-41](https://user-images.githubusercontent.com/4853097/145864038-2d596015-278f-48f5-847d-16b031b6cb9d.png)

Note that to get this to work, I had to disable the computation of the RGB values (I get `RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x256 and 283x128)`, which I solved by returning early here https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/8285dd09040fa0829c1fcb55e4d9d7e71b43d821/model/nerf.py#L367-368. It would be good if you could tell me whether this is a bug in my code or simply a dimensionality mismatch since we are not using camera rays).

However, I had some issues with a custom training of mine, so there might be some issues with the code (although most likely the data I am using might be too noisy for it to learn a good depth representation).

Looking forward to your comments!

**Comment by chenhsuanlin** [comment]
Hi @martinarroyo, thanks for the feedback! Could you elaborate more on the specific issue you're having?
Regarding the matmul error, this is because you have this line `opt.nerf.view_dep = False` after initializing the network but before calling forward, so there's a dimensionality mismatch in [this block](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L369). Alternatively, you could just pass in an arbitrary dimension-matching tensor for `ray_unit`, since it only affects the RGB and not of concern in your case. Hope this helps!

**Comment by martinarroyo** [comment]
Thanks for the quick feedback. I will try that, but as you said this is only for RGB, so it's only necessary so that I don't have to modify existing code. My main concern is whether you see some issues with this code, because, even though it works for this model, I am not sure if I got it right in the general case.

**Comment by chenhsuanlin** [comment]
I don't see any issue with your script. I would write it the same way 🙂
It's worth noting that marching cubes only makes sense when the 3D space is metric, as in the synthetic object data. It wouldn't make as much sense for NDC parametrization (e.g. the real-world forward-facing scenes).

**Comment by martinarroyo** [comment]
Thanks. By the way, if you think this is could be useful for someone else I wouldn't mind making a PR out of it.

At the moment I am seeing some issues with a reconstruction of my own data. I used Colmap to extract the poses (though in fact it works also fine with identity as initialization) and when rendering RGB everything looks OK (depth is a bit off, but it's also fine). However, when I reconstruct the image, the shape is 'skewed' along the z axis. I suppose there is some issue with the coordinates that I am querying, but since I don't think I am using NDC (I inherit my configuration from `options/nerf_blender.yaml`, which has `ndc: false`), I am not sure what it could be. Any tips are appreciated!

**Comment by chenhsuanlin** [comment]
Thanks! A PR would be cool 😎
I'm guessing you're working on forward-facing scenes? If so, I think this would be more or less expected even without NDC. This mostly has to do with sampling strategies for volume rendering. For forward-facing scenes, sampling linearly in the inverse depth space allows NeRF/BARF to concentrate samples closer to the cameras. This type of parametrization is more suitable for view synthesis and less aimed for reconstructing 3D surfaces, as the exact depth/shape of scenes is less important as long as the rendering is plausible. Sampling in the metric space would probably give you better (less skewed) results, but it would require much denser samples to really find the actual underlying surfaces. This is still an active line of research as of now!

**Comment by teachyourselfcoding** [comment]
@martinarroyo An PR would be useful! I'm further behind the line when it comes to this field and I'm looking for ways to convert my checkpoints to a 3D file. Cheers!

**Comment by martinarroyo** [comment]
Apologies for the delay. I just added #16 for review.

**Comment by chenhsuanlin** [comment]
Thanks @martinarroyo! I've made some minor changes to the PR -- I'm dumping the 3D mesh to an .obj file instead of visualizing on-screen as it would break on remote servers. The marching cubes hyperparameters are also moved to the yaml files so they could be overridden from the command line. The current merged version should be good to go 😄
cc @teachyourselfcoding

**Comment by martinarroyo** [comment]
Perfect, thanks! On another note, I am curious about what you said regarding the way that NeRF arranges the 3D space internally, and how this affects the quality of the 3D reconstruction. I guess that a first strategy is simply to get images from all viewpoints around the object, but I was wondering if you could point me to some literature that has analyzed these issues. Thanks in advance!

**Comment by chenhsuanlin** [comment]
I'm not very sure what you meant by arranging the 3D space? If you're talking about sampling and parametrization, the **Parametrization** section on pages 1-2 of [Mip-NeRF 360](https://arxiv.org/pdf/2111.12077.pdf) has a nice summary on its importance. Hope this one helps!

**Comment by martinarroyo** [comment]
Thanks!

**Comment by gs14iitbbs** [comment]
Hi, 

For these iPhone images example shown below:

![0002](https://user-images.githubusercontent.com/25165333/185554458-392e88bf-5a79-47ee-9f2c-197c1cc2c68b.jpg)

I  am getting wierd 3D mesh like this: 

![image](https://user-images.githubusercontent.com/25165333/185554310-7b807cdd-dbaf-4881-a367-7ca9968938f7.png)


Does anyone have idea what could be the reason?  FYI: I only changed the camera parameters.

**Comment by chenhsuanlin** [comment]
Hi @gs14iitbbs, is this a 360˚ object-centric capture? If so, NDC shouldn't be used as it's pretty specific for forward-facing scenes only. Please see #19 for related discussions.
